server {
    set_by_lua $serverName 'return os.getenv("DAVIS_SERVER_NAME")';
    server_name $serverName;
    listen 8080;
    access_log off;

    root /var/www/davis/public/;
    index index.php;

    rewrite ^/.well-known/caldav /dav/ redirect;
    rewrite ^/.well-known/carddav /dav/ redirect;

    charset utf-8;

    location ~ /(\.ht) {
        deny all;
        return 404;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^(.+\.php)(.*)$ {
        set_by_lua $upstream_host 'return os.getenv("DAVIS_UPSTREAM") or "127.0.0.1:9000"';
        try_files       $fastcgi_script_name =404;
        include         fastcgi_params;
        fastcgi_pass    $upstream_host;
        fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO        $fastcgi_path_info;
        fastcgi_split_path_info  ^(.+\.php)(.*)$;
    }
}

