---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Image Versions
description: Takes an upstream version string and returns various version types

inputs:
  upstream-version:
    description: Upstream Version
    required: true

outputs:
  is-valid-semver:
    description: If version is valid semantic versioning
    value: ${{ steps.version.outputs.is-valid-semver }}
  semantic:
    description: Semantic Version
    value: ${{ steps.version.outputs.semantic }}
  raw:
    description: Raw Version
    value: ${{ steps.version.outputs.raw }}
  upstream:
    description: Upstream Version
    value: ${{ steps.version.outputs.upstream }}

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 22.x

    - name: Install Semver
      shell: bash
      run: npm install semver

    - name: Determine Image Versions
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: version
      with:
        script: |
          const semver = require('semver');

          // Strip the v prefix and pre-release info
          function sanitize(version) {
              return version.replace(/^v/, '').split('-')[0];
          }

          function calver() {
              const now = new Date();
              return `${now.getFullYear()}.${now.getMonth() + 1}.${now.getDate()}`;
          }

          const upstreamVersion = '${{ inputs.upstream-version }}';
          const strictSemverRegex = /^v?(\d+(\.\d+)?(\.\d+)?)/;

          const parsedVersion = strictSemverRegex.exec(upstreamVersion);
          const isValidSemver = parsedVersion !== null;
          const parsedSemver = isValidSemver ? semver.coerce(parsedVersion[0]) : null;
          const semanticVersion = isValidSemver ? `${parsedSemver.major}.${parsedSemver.minor}.${parsedSemver.patch}` : calver();
          const rawVersion = isValidSemver ? sanitize(upstreamVersion) : upstreamVersion;

          core.setOutput('is-valid-semver', isValidSemver);
          core.setOutput('semantic', semanticVersion);
          core.setOutput('raw', rawVersion);
          core.setOutput('upstream', upstreamVersion);
