---
# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Bake Options
description: Takes an app and returns various fields from its docker-bake.hcl file

inputs:
  app:
    description: Application name
    required: true

outputs:
  platforms:
    description: Platforms
    value: ${{ steps.bake.outputs.platforms }}
  version:
    description: Version
    value: ${{ steps.bake.outputs.version }}

runs:
  using: composite
  steps:
    - name: Bake Options
      id: bake
      shell: bash
      run: |
        BAKE_OPTS=$(docker buildx bake --file ./apps/${{ inputs.app }}/docker-bake.hcl image-all --print 2>/dev/null)

        PLATFORMS=$(jq --raw-output --compact-output '.target."image-all".platforms' <<< "$BAKE_OPTS")
        echo "platforms=${PLATFORMS}" >> $GITHUB_OUTPUT

        VERSION=$(jq --raw-output --compact-output '.target."image-all".args.VERSION' <<< "$BAKE_OPTS")
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
