---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Retry Release

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  apps:
    name: Get App Inventory
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.inventory.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get App Inventory
        uses: ./.github/actions/app-inventory
        id: inventory

  retry:
    if: ${{ needs.apps.outputs.apps != '[]' }}
    name: Retry Release
    runs-on: ubuntu-latest
    needs: apps
    strategy:
      matrix:
        app: ${{ fromJSON(needs.apps.outputs.apps) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Vars
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: vars
        with:
          script: |
            core.setOutput('repository-owner', '${{ github.repository_owner }}'.toLowerCase());

      - name: Generate Token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@fb28c2b6339dcd94da6e4cbcbc5e888961f6f8c3 # v3.9.0

      - name: Install regctl
        uses: regclient/actions/regctl-installer@4d6888fcc4842c9630f60ebc91715a45dd9bd7a3 # main

      - name: Get Bake Options
        id: bake-options
        uses: ./.github/actions/bake-options
        with:
          app: ${{ matrix.app }}

      - name: Get Container Registry Version
        id: registry
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          if ! version=$(regctl image inspect ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ matrix.app }}:rolling \
              | jq --raw-output '.config.Labels["org.opencontainers.image.version"]' 2>/dev/null) || [[ -z "${version}" ]];
          then
              echo "Failed to get registry version for ${{ matrix.app }}"
              exit 1
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT

      - if: ${{ steps.bake-options.outputs.version != steps.registry.outputs.version }}
        name: Retry Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh workflow run release.yaml \
              --repo ${{ github.repository }} \
              -f app=${{ matrix.app }} \
              -f release=true

          {
              echo '## Retrying Release'
              echo
              echo '| Container Name | Actual Version | Expected Version |'
              echo '|----------------|------------------|----------------|'
              echo '| `${{ matrix.app }}` | `${{ steps.registry.outputs.version }}` | `${{ steps.bake-options.outputs.version }}` |'
          } >> $GITHUB_STEP_SUMMARY
